<Project Sdk="Microsoft.NET.Sdk">
  <Import Condition="Exists('..\..\.config\local\HollowKnightPath1221.props')" Project="..\..\.config\local\HollowKnightPath1221.props" />

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <HKVersionConstant>V1221</HKVersionConstant>
    <HKLocalPropsName>HollowKnightPath1221.props</HKLocalPropsName>
  </PropertyGroup>

  <Import Project="HK.Common.targets" />
</Project>
