<Project Sdk="Microsoft.NET.Sdk">
  <Import Condition="Exists('..\..\.config\local\HollowKnightPath1578.props')" Project="..\..\.config\local\HollowKnightPath1578.props" />

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <HKVersionConstant>V1578</HKVersionConstant>
    <HKLocalPropsName>HollowKnightPath1578.props</HKLocalPropsName>
  </PropertyGroup>

  <ItemGroup Condition="'$(HollowKnightManagedFolder)' != ''">
    <Reference Include="MMHOOK_Assembly-CSharp" Condition="Exists('$(HollowKnightManagedFolder)\MMHOOK_Assembly-CSharp.dll')">
      <HintPath>$(HollowKnightManagedFolder)\MMHOOK_Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule" Condition="Exists('$(HollowKnightManagedFolder)\UnityEngine.InputLegacyModule.dll')">
      <HintPath>$(HollowKnightManagedFolder)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule" Condition="Exists('$(HollowKnightManagedFolder)\UnityEngine.ImageConversionModule.dll')">
      <HintPath>$(HollowKnightManagedFolder)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Import Project="HK.Common.targets" />
</Project>
